apiVersion: v1
kind: Pod
metadata:
  name: pod-for-node2
spec:
  containers:
    - name: contic
      image: nginx
      ports:
        - containerPort: 80
  nodeName: node2       # by default 'nodeName' isn't specified. Thus scheduler can chose any accessible
                        # but you can specify node yourself
