apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: word
spec:
  replicas: 2
  selector:
    matchLabels:
      app: word
  template:
    metadata:
      labels:
        app: word
    spec:
      containers:
        - image: wordpress:5.6 # image ver > 5.6 won't work due to changing wp-config.php 
          name: wordpress
          env:
          - name: WORDPRESS_DB_HOST
            value: mysql-svc:3306
          - name: WORDPRESS_DB_PASSWORD
            value: "1234567"
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: pvc-wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpres-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: word

