apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy 
spec:
  replicas: 1
  selector:
    matchLabels:
      lemax: one 
  template:
    metadata:
      labels:
        lemax: one
    spec:
      containers:
        - image: nginx
          name: nginx
