apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-ver1
spec:
  containers:
    - name: contic
      image: nginx
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: mynode # label of the node
              operator: In
              values:
                - testlab # label of the node
