apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-grafana
  namespace: monitoring
spec:
  storageClassName: pv-grafana
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
