#create a deployment that meets the app's specifications. Then, we need to expose the application using a NodePort service. This setup should meet the following criteria:
#    All objects should be in the pizza namespace. This namespace already exists in the cluster.
#    The deployment should be named pizza-deployment.
#    The deployment should have 3 replicas.
#    The deployment's pods should have one container using the linuxacademycontent/pizza-service image with the tag 1.14.6.
#    Run the container with the command nginx.
#    Run the container with the arguments "-g", "daemon off;".
#    The pods should expose port 80 to the cluster.
#    The pods should be configured to periodically check the /healthz endpoint on port 8081, and restart automatically if the request fails.
#    The pods should not receive traffic from the service until the / endpoint on port 80 responds successfully.
#    The service should be named pizza-service.
#    The service should forward traffic to port 80 on the pods.
#    The service should be exposed externally by listening on port 30080 on each node.
#    Checking: curl localhost:30080


apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-deployment
  namespace: pizza
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pizza
  template:
    metadata:
      labels:
        app: pizza
    spec:
      containers:
        - name: contic-pizza
          image: linuxacademycontent/pizza-service:1.14.6
          command: ["nginx"]
          args: ["-g", "daemon off;"]
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: pizza-service
  namespace: pizza
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector: 
    app: pizza

