apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
    - name: contic
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234567"
  nodeName: node3 # specify the node to be used
                  # nodeName takes precedence over restrictions(like taints) and all methods for node selection
                  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodename
                  
