apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: run 
  template:
    metadata:
      labels:
        app: run
    spec:
      containers:
        - image: contic
          name: httpd
