apiVersion: v1
kind: Service
metadata:
  name: prometheus-dashboard
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus-server
  ports:
    - port: 8080
      targetPort: 9090
