apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-prometheus
  namespace: monitoring
spec:
  storageClassName: nfs-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
