apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elastic
spec:
  storageClassName: elastic-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /elastic-hdd
