# this is ingress rule with access using IP of nginx-controller
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: one-backand-ingress
spec:
  backend:
    serviceName: web-apache
    servicePort: 80

# check using for example curl:
# curl <nginx-controller-ip>

