apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-java
  namespace: default
spec:
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: alex
          image: htech7x/grpc-java
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-java
  namespace: default
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
    name: grpc
  selector:
    app: java
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: grpc
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: grpc-tls
      namespace: gloo-system
  virtualHost:
    domains:
    - hello.example.com
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: default-grpc-java-50051
              namespace: gloo-system
