apiVersion: v1
kind: ServiceAccount
metadata:
  name: htech7x
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: htech7x-permissive
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-permissive
subjects:
- kind: ServiceAccount
  name: htech7x
  namespace: default
