apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: nfs
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME # don't change
              value: my-nfs-provisioner # should be same like in StorageClass
            - name: NFS_SERVER # don't change
              value: 172.31.88.224 # NFS server IP
            - name: NFS_PATH # don't change
              value: /nfs # shared folder on NFS server
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.31.88.224
            path: /nfs
