apiVersion: v1
kind: Pod
metadata:
  name: pod-sc-test
spec:
  containers:
    - name: alex
      image: busybox
      command: ["/bin/sh","-c","sleep 3600"]
      volumeMounts:
        - name: vol
          mountPath: /hdd
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: pvc-sc
