apiVersion: v1
kind: Pod
metadata:
  name: multi
  namespace: my-space
spec:
  volumes:
    - name: disk
      emptyDir: {}
  containers:
    - image: nginx
      name: cont-nginx
      volumeMounts:
        - name: disk
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
    - image: busybox
      name: cont-linux
      volumeMounts:
        - name: disk
          mountPath: /hdd
      command: ["/bin/sh", -c]
      args:
        - while true; do
          date >> /hdd/index.html;
          sleep 1;
          done
