apiVersion: v1
kind: Pod
metadata:
  name: all-env-from-secret
spec:
  containers:
    - name: contic
      image: busybox
      command: ["/bin/sh","-c","sleep 300"]
      envFrom:
        - secretRef:
            name: my-secret



