apiVersion: v1
kind: Pod
metadata:
  name: single-env-from-secret
spec:
  containers:
    - name: contic
      image: busybox
      command: ["/bin/sh","-c","sleep 300"]
      env:
        - name: passwd
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: passwd



