apiVersion: v1
kind: Pod
metadata:
  name: secret-from-volume
spec:
  containers:
    - name: contic
      image: busybox
      command: ["/bin/sh","-c","sleep 300"]
      volumeMounts:
        - name: sec-vol
          mountPath: /disk
  volumes:
    - name: sec-vol
      secret:
        secretName: my-secret



